FROM python:3.11.4

#Makes workdir in docker container
WORKDIR /app 

#Copies to the docker container
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
